In [1]:
?array

In [2]:
student.scores <- array(c(23, 54, 73, 98, 45, 62), dim=c(3, 2))

student.scores

[,1] [,2]
[1,] 23   98  
[2,] 54   45  
[3,] 73   62

In [3]:
class(student.scores)

[1] "matrix"

In [4]:
is.matrix(student.scores)

[1] TRUE

In [5]:
is.array(student.scores)

[1] TRUE

In [6]:
is.vector(student.scores)

[1] FALSE

In [7]:
student.scores.midterm <- array(c(23, 54, 73, 98, 45, 62), dim=c(3, 2),
                               dimnames=list(c("Julia", "James", "Joe"), c("Math", "English")))

student.scores.midterm

Math English
Julia 23   98     
James 54   45     
Joe   73   62

In [8]:
student.scores.final <- array(c(78, 34, 88, 56, 65, 75), dim=c(3, 2),
                               dimnames=list(c("Julia", "James", "Joe"), c("Math", "English")))

student.scores.final

Math English
Julia 78   56     
James 34   65     
Joe   88   75

In [9]:
all.scores <- array(c(student.scores.midterm, student.scores.final), dim = c(3, 2, 2))

all.scores

, , 1

     [,1] [,2]
[1,]   23   98
[2,]   54   45
[3,]   73   62

, , 2

     [,1] [,2]
[1,]   78   56
[2,]   34   65
[3,]   88   75

In [10]:
print(all.scores)

, , 1

     [,1] [,2]
[1,]   23   98
[2,]   54   45
[3,]   73   62

, , 2

     [,1] [,2]
[1,]   78   56
[2,]   34   65
[3,]   88   75



In [11]:
all.scores <- array(c(student.scores.midterm, student.scores.final), 
                    dim = c(3, 2, 2),
                    dimnames = list(c("Julia", "James", "Joe"), 
                                    c("Math", "English"),
                                    c("Midterm", "Final")))

print(all.scores)

, , Midterm

      Math English
Julia   23      98
James   54      45
Joe     73      62

, , Final

      Math English
Julia   78      56
James   34      65
Joe     88      75



In [12]:
is.array(all.scores)

[1] TRUE

In [13]:
is.matrix(all.scores)

[1] FALSE

In [14]:
dim(all.scores)

[1] 3 2 2

In [15]:
all.scores[1, 1, 1]

[1] 23

In [16]:
all.scores["James", , "Final"]

Math English 
     34      65

In [17]:
all.scores["James", "Math", ]

Midterm   Final 
     54      34

In [18]:
all.scores[c("James", "Joe"), "Math", ]

Midterm Final
James 54      34   
Joe   73      88

In [19]:
all.scores[, , "Final"]

Math English
Julia 78   56     
James 34   65     
Joe   88   75

In [20]:
all.scores[, , "Final"] * 1.1

Math English
Julia 85.8 61.6   
James 37.4 71.5   
Joe   96.8 82.5

In [21]:
all.scores[, , "Final"] <- all.scores[, , "Final"] * 1.1

print(all.scores)

, , Midterm

      Math English
Julia   23      98
James   54      45
Joe     73      62

, , Final

      Math English
Julia 85.8    61.6
James 37.4    71.5
Joe   96.8    82.5

