In [1]:
?matrix

In [2]:
matrix.a <- matrix(c(100, 200, 300, 400), ncol=2)

matrix.a

[,1] [,2]
[1,] 100  300 
[2,] 200  400

In [3]:
class(matrix.a)

[1] "matrix"

In [4]:
is.matrix(matrix.a)

[1] TRUE

In [5]:
matrix.a[1,1]

[1] 100

In [6]:
matrix.a[1,2]

[1] 300

In [7]:
matrix.a[2,1]

[1] 200

In [8]:
matrix.a[2,2]

[1] 400

In [9]:
matrix.a[1,]

[1] 100 300

In [10]:
matrix.a[,2]

[1] 300 400

In [11]:
matrix.a[2,2] <- 444

matrix.a

[,1] [,2]
[1,] 100  300 
[2,] 200  444

In [12]:
matrix.b <- matrix(nrow=2, ncol=3)

matrix.b

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

In [13]:
matrix.b[2,3] <- 111
matrix.b[1,1] <- 555

matrix.b

[,1] [,2] [,3]
[1,] 555  NA    NA 
[2,]  NA  NA   111

In [14]:
matrix.c <- matrix(c(111, 222, 333, 444, 555, 666), nrow=2, byrow=FALSE)

matrix.c

[,1] [,2] [,3]
[1,] 111  333  555 
[2,] 222  444  666

In [15]:
matrix.c <- matrix(c(111, 222, 333, 444, 555, 666), nrow=2, byrow=TRUE)

matrix.c

[,1] [,2] [,3]
[1,] 111  222  333 
[2,] 444  555  666

In [16]:
car.quantities = matrix(101:106, c(2, 3))

car.quantities

[,1] [,2] [,3]
[1,] 101  103  105 
[2,] 102  104  106

In [17]:
car.quantities <- matrix(101:106, c(2, 3), 
                         dimnames=list(c("Honda", "Ford"), c("White", "Silver", "Red")))

car.quantities

White Silver Red
Honda 101   103    105
Ford  102   104    106

In [18]:
dim(car.quantities)

[1] 2 3

In [19]:
nrow(car.quantities)

[1] 2

In [20]:
ncol(car.quantities)

[1] 3

In [21]:
length(car.quantities)

[1] 6

In [22]:
rownames(car.quantities)

[1] "Honda" "Ford"

In [23]:
colnames(car.quantities)

[1] "White"  "Silver" "Red"

In [24]:
dimnames(car.quantities)

[[1]]
[1] "Honda" "Ford" 

[[2]]
[1] "White"  "Silver" "Red"

In [25]:
fruits <- matrix(c(4, 5, 1, 7, 9, 3, 4, 5, 9), c(3, 3), 
                 dimnames=list(c("Apples", "Oranges", "Bananas"), c("Organic", "Regular", "Local")))

fruits

Organic Regular Local
Apples  4       7       4    
Oranges 5       9       5    
Bananas 1       3       9

In [26]:
fruits[1, 3]

[1] 4

In [27]:
fruits[-1, 3]

Oranges Bananas 
      5       9

In [28]:
fruits["Apples", "Regular"]

[1] 7

In [29]:
fruits[3, "Organic"]

[1] 1

In [30]:
fruits[3, c("Organic", "Regular")]

Organic Regular 
      1       3

In [31]:
fruits[c("Apples", "Oranges"), 1:2]

Organic Regular
Apples  4       7      
Oranges 5       9

In [32]:
matrix.a <- matrix(c(100, 200, 300, 400), nrow=2, ncol=2)

matrix.a

[,1] [,2]
[1,] 100  300 
[2,] 200  400

In [33]:
matrix.b <- matrix(nrow=3, ncol=3)

matrix.b

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA  
[3,] NA   NA   NA

In [34]:
matrix.b[2:3, 2:3] = matrix.a

matrix.b

[,1] [,2] [,3]
[1,] NA    NA   NA 
[2,] NA   100  300 
[3,] NA   200  400

In [35]:
matrix.a <- matrix(c(10, 20, 30, 40), nrow=2, ncol=2)

matrix.a

[,1] [,2]
[1,] 10   30  
[2,] 20   40

In [36]:
matrix.a * 2

[,1] [,2]
[1,] 20   60  
[2,] 40   80

In [37]:
matrix.a / 3

[,1]     [,2]    
[1,] 3.333333 10.00000
[2,] 6.666667 13.33333

In [38]:
matrix.b <- matrix(c(1, 2, 3, 4), nrow=2, ncol=2)

matrix.b

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [39]:
matrix.a + matrix.b

[,1] [,2]
[1,] 11   33  
[2,] 22   44

In [40]:
matrix.a * matrix.b

[,1] [,2]
[1,] 10    90 
[2,] 40   160

In [41]:
matrix.c <- matrix(1:6, nrow=2)

matrix.c

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [42]:
matrix.a + matrix.c

ERROR: Error in matrix.a + matrix.c: non-conformable arrays


In [43]:
matrix.result <- matrix.a %*% matrix.c

matrix.result

[,1] [,2] [,3]
[1,]  70  150  230 
[2,] 100  220  340

In [44]:
identical(matrix.c, matrix.result)

[1] FALSE

In [45]:
matrix.d = matrix(c(70, 150, 230, 100, 220, 340), nrow=2, byrow=TRUE)

matrix.d

[,1] [,2] [,3]
[1,]  70  150  230 
[2,] 100  220  340

In [46]:
identical(matrix.d, matrix.result)

[1] TRUE

In [47]:
matrix.d

[,1] [,2] [,3]
[1,]  70  150  230 
[2,] 100  220  340

In [48]:
dim(matrix.d) <- c(3, 2)

matrix.d

[,1] [,2]
[1,]  70  220 
[2,] 100  230 
[3,] 150  340

In [49]:
matrix.a

[,1] [,2]
[1,] 10   30  
[2,] 20   40

In [50]:
matrix.c

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [51]:
matrix.combined <- c(matrix.a, matrix.c)

matrix.combined

[1] 10 20 30 40  1  2  3  4  5  6

In [52]:
matrix.columnbind <- cbind(matrix.a, matrix.c)

matrix.columnbind

[,1] [,2] [,3] [,4] [,5]
[1,] 10   30   1    3    5   
[2,] 20   40   2    4    6

In [53]:
matrix.rowbind <- rbind(matrix.a, matrix.c)

matrix.rowbind

ERROR: Error in rbind(matrix.a, matrix.c): number of columns of matrices must match (see arg 2)


In [54]:
t(matrix.c)

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6

In [55]:
matrix.rowbind <- rbind(matrix.a, t(matrix.c))

matrix.rowbind

[,1] [,2]
[1,] 10   30  
[2,] 20   40  
[3,]  1    2  
[4,]  3    4  
[5,]  5    6

In [56]:
dim(matrix.rowbind) <- c(2, 5)

matrix.rowbind

[,1] [,2] [,3] [,4] [,5]
[1,] 10   1     5   40   4   
[2,] 20   3    30    2   6

In [57]:
dim(matrix.rowbind) <- c(2, 4)

matrix.rowbind

ERROR: Error in dim(matrix.rowbind) <- c(2, 4): dims [product 8] do not match the length of object [10]


In [58]:
reduced.m <- matrix.rowbind[1,1:3]

reduced.m

[1] 10  1  5

In [59]:
class(reduced.m)

[1] "numeric"

In [60]:
reduced.m <- matrix.rowbind[1,1:3, drop=FALSE]

reduced.m

[,1] [,2] [,3]
[1,] 10   1    5

In [61]:
class(reduced.m)

[1] "matrix"

In [62]:
weight <- c(45, 52, 67, 53, 56, 49, 52, 62, 75)

weight

[1] 45 52 67 53 56 49 52 62 75

In [63]:
weight.matrix = matrix(weight, nrow=3, ncol=3, 
                       dimnames=list(c("row1", "row2", "row3"), c("col1", "col2","col3")))

weight.matrix

col1 col2 col3
row1 45   53   52  
row2 52   56   62  
row3 67   49   75

In [64]:
rowSums(weight.matrix)

row1 row2 row3 
 150  170  191

In [65]:
colSums(weight.matrix)

col1 col2 col3 
 164  158  189

In [66]:
rowMeans(weight.matrix)

row1     row2     row3 
50.00000 56.66667 63.66667

In [67]:
colMeans(weight.matrix)

col1     col2     col3 
54.66667 52.66667 63.00000

In [68]:
mobile.brands <- matrix(c("apple", "samsung", "lg", "oppo", "mi", 
                          "vivo", "motorola", "sony", "realme"), 
                          nrow = 3, ncol = 3)

mobile.brands

[,1]    [,2] [,3]    
[1,] apple   oppo motorola
[2,] samsung mi   sony    
[3,] lg      vivo realme

In [69]:
random.matrix <- matrix(c(1, TRUE, "isabela", 3+2i), nrow=2)

random.matrix

[,1] [,2]   
[1,] 1    isabela
[2,] TRUE 3+2i